import React, { useState, useCallback, useEffect } from 'react';
import { Battery, Power, Zap, Settings, AlertTriangle, TrendingUp, TrendingDown, Clock, Eye, Save } from 'lucide-react';

const MIC3X2XPowerManager = () => {
  const [powerConfig, setPowerConfig] = useState({
    sleepConditions: {
      uart: false,
      obd: false,
      voltage: { enabled: false, threshold: 0.0, timer: 0 },
      ignition: false
    },
    wakeConditions: {
      uart: false,
      obd: true,
      voltageDeepDrop: { enabled: true, threshold: 4.0 },
      ignition: false,
      voltageChange: { enabled: false, direction: 'both', threshold: 0.5, interval: 2000 }
    },
    voltageMonitoring: {
      realTimeDisplay: false,
      sampleRate: 4, // ms
      calibration: 12.0
    }
  });

  const [voltageReading, setVoltageReading] = useState(12.1);
  const [isMonitoring, setIsMonitoring] = useState(false);
  const [powerStatus, setPowerStatus] = useState('normal');
  const [voltageHistory, setVoltageHistory] = useState([]);

  // Voltage change wake directions
  const VOLTAGE_DIRECTIONS = [
    { value: 'rise', label: '+', description: 'Wake on voltage rise only' },
    { value: 'drop', label: '-', description: 'Wake on voltage drop only' },
    { value: 'both', label: '±', description: 'Wake on voltage rise or drop' }
  ];

  const updateSleepCondition = (condition, value) => {
    setPowerConfig(prev => ({
      ...prev,
      sleepConditions: {
        ...prev.sleepConditions,
        [condition]: typeof value === 'object' ? { ...prev.sleepConditions[condition], ...value } : value
      }
    }));
  };

  const updateWakeCondition = (condition, value) => {
    setPowerConfig(prev => ({
      ...prev,
      wakeConditions: {
        ...prev.wakeConditions,
        [condition]: typeof value === 'object' ? { ...prev.wakeConditions[condition], ...value } : value
      }
    }));
  };

  const generatePowerCommands = () => {
    const commands = [];
    
    // Sleep conditions
    if (powerConfig.sleepConditions.voltage.enabled) {
      commands.push(
        `VT PDVS ${powerConfig.sleepConditions.voltage.threshold}, ${powerConfig.sleepConditions.voltage.timer}`
      );
    }
    
    // Wake conditions
    if (powerConfig.wakeConditions.voltageDeepDrop.enabled) {
      commands.push(
        `VT VDWK ${powerConfig.wakeConditions.voltageDeepDrop.threshold}, 20`
      );
    }
    
    // Voltage change wake (new feature)
    if (powerConfig.wakeConditions.voltageChange.enabled) {
      const direction = powerConfig.wakeConditions.voltageChange.direction === 'rise' ? '+' :
                      powerConfig.wakeConditions.voltageChange.direction === 'drop' ? '-' : '';
      commands.push(
        `VT VLCW ${direction}${powerConfig.wakeConditions.voltageChange.threshold}, ${powerConfig.wakeConditions.voltageChange.interval}`
      );
    }
    
    return commands;
  };

  const generatePowerManageQuery = () => {
    return 'VT POWERMANAGE';
  };

  const generateVoltageReadCommand = () => {
    return 'VT VLRD';
  };

  const startVoltageMonitoring = () => {
    setIsMonitoring(true);
    // Simulate voltage readings
    const interval = setInterval(() => {
      const baseVoltage = 12.1;
      const variation = (Math.random() - 0.5) * 0.4; // ±0.2V variation
      const newReading = Math.max(8.0, Math.min(16.0, baseVoltage + variation));
      setVoltageReading(newReading);
      
      setVoltageHistory(prev => {
        const newHistory = [...prev, { time: Date.now(), voltage: newReading }];
        return newHistory.slice(-100); // Keep last 100 readings
      });
      
      // Determine power status based on voltage
      if (newReading < 10.0) {
        setPowerStatus('critical');
      } else if (newReading < 11.5) {
        setPowerStatus('low');
      } else {
        setPowerStatus('normal');
      }
    }, powerConfig.voltageMonitoring.sampleRate);

    // Store interval ID for cleanup
    window.voltageInterval = interval;
  };

  const stopVoltageMonitoring = () => {
    setIsMonitoring(false);
    if (window.voltageInterval) {
      clearInterval(window.voltageInterval);
      window.voltageInterval = null;
    }
  };

  const exportPowerConfig = () => {
    const commands = generatePowerCommands();
    const configText = [
      '# MIC3X2X Power Management Configuration',
      '# Generated by MIC3X2X Power Manager',
      '',
      '# Query current power management status',
      generatePowerManageQuery(),
      '',
      '# Power management commands',
      ...commands,
      '',
      '# Voltage monitoring commands',
      generateVoltageReadCommand(),
    ].join('\n');

    const blob = new Blob([configText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'mic3x2x_power_config.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  const PowerConditionCard = ({ title, icon, children, status = 'normal' }) => {
    const statusColors = {
      normal: 'border-gray-200 bg-white',
      warning: 'border-yellow-300 bg-yellow-50',
      critical: 'border-red-300 bg-red-50',
      active: 'border-green-300 bg-green-50'
    };

    return (
      <div className={`border-2 rounded-lg p-4 ${statusColors[status]}`}>
        <div className="flex items-center space-x-2 mb-3">
          {icon}
          <h3 className="font-semibold text-gray-800">{title}</h3>
        </div>
        {children}
      </div>
    );
  };

  const VoltageChart = () => {
    if (voltageHistory.length === 0) return null;

    const maxVoltage = Math.max(...voltageHistory.map(h => h.voltage));
    const minVoltage = Math.min(...voltageHistory.map(h => h.voltage));
    const range = maxVoltage - minVoltage || 1;

    return (
      <div className="h-32 border rounded bg-gray-50 p-2 relative">
        <div className="text-xs text-gray-500 mb-1">Voltage History (Last 100 readings)</div>
        <svg className="w-full h-24">
          <polyline
            points={voltageHistory.map((point, index) => 
              `${(index / (voltageHistory.length - 1)) * 100},${100 - ((point.voltage - minVoltage) / range) * 80}`
            ).join(' ')}
            fill="none"
            stroke="#3B82F6"
            strokeWidth="2"
            vectorEffect="non-scaling-stroke"
            style={{ transform: 'scale(1, 1)' }}
          />
        </svg>
        <div className="absolute bottom-0 left-0 text-xs text-gray-400">
          {minVoltage.toFixed(1)}V
        </div>
        <div className="absolute top-6 left-0 text-xs text-gray-400">
          {maxVoltage.toFixed(1)}V
        </div>
      </div>
    );
  };

  return (
    <div className="max-w-6xl mx-auto p-6 bg-gray-50 min-h-screen">
      <div className="bg-white rounded-lg shadow-lg p-6">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center space-x-3">
            <Battery className="text-green-600" size={28} />
            <h1 className="text-2xl font-bold text-gray-800">MIC3X2X Power Management</h1>
            <div className="text-sm text-gray-500">
              Enhanced voltage monitoring & wake features
            </div>
          </div>
          <div className="flex space-x-2">
            <button
              onClick={exportPowerConfig}
              className="flex items-center space-x-2 bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600"
            >
              <Save size={16} />
              <span>Export Config</span>
            </button>
          </div>
        </div>

        {/* Current Voltage Display */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
          <div className={`p-4 rounded-lg border-2 ${
            powerStatus === 'critical' ? 'border-red-500 bg-red-50' :
            powerStatus === 'low' ? 'border-yellow-500 bg-yellow-50' :
            'border-green-500 bg-green-50'
          }`}>
            <div className="flex items-center space-x-3">
              <Battery className={
                powerStatus === 'critical' ? 'text-red-600' :
                powerStatus === 'low' ? 'text-yellow-600' :
                'text-green-600'
              } size={24} />
              <div>
                <div className="text-2xl font-bold">{voltageReading.toFixed(1)}V</div>
                <div className="text-sm text-gray-600">Current Voltage</div>
              </div>
            </div>
          </div>
          
          <div className="p-4 rounded-lg border border-gray-200">
            <div className="flex items-center space-x-2 mb-2">
              <Eye size={16} />
              <span className="font-medium">Voltage Monitoring</span>
            </div>
            <div className="space-x-2">
              <button
                onClick={isMonitoring ? stopVoltageMonitoring : startVoltageMonitoring}
                className={`px-3 py-1 rounded text-sm ${
                  isMonitoring 
                    ? 'bg-red-500 text-white hover:bg-red-600' 
                    : 'bg-green-500 text-white hover:bg-green-600'
                }`}
              >
                {isMonitoring ? 'Stop' : 'Start'} Monitor
              </button>
            </div>
          </div>
          
          <div className="p-4 rounded-lg border border-gray-200">
            <div className="text-sm text-gray-600">Sample Rate</div>
            <div className="text-lg font-semibold">{powerConfig.voltageMonitoring.sampleRate}ms</div>
            <div className="text-xs text-gray-500">VLRD command interval</div>
          </div>
        </div>

        {/* Voltage Chart */}
        {isMonitoring && <VoltageChart />}

        {/* Sleep Conditions */}
        <div className="mb-8">
          <h2 className="text-xl font-bold text-gray-800 mb-4 flex items-center space-x-2">
            <Power className="text-red-600" size={20} />
            <span>Sleep Conditions</span>
          </h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <PowerConditionCard
              title="UART Silence"
              icon={<Settings className="text-gray-600" size={16} />}
              status={powerConfig.sleepConditions.uart ? 'active' : 'normal'}
            >
              <div className="flex items-center">
                <input
                  type="checkbox"
                  checked={powerConfig.sleepConditions.uart}
                  onChange={(e) => updateSleepCondition('uart', e.target.checked)}
                  className="mr-2"
                />
                <label className="text-sm">Enter sleep when UART is silent</label>
              </div>
            </PowerConditionCard>

            <PowerConditionCard
              title="OBD Bus Silence"
              icon={<Settings className="text-gray-600" size={16} />}
              status={powerConfig.sleepConditions.obd ? 'active' : 'normal'}
            >
              <div className="flex items-center">
                <input
                  type="checkbox"
                  checked={powerConfig.sleepConditions.obd}
                  onChange={(e) => updateSleepCondition('obd', e.target.checked)}
                  className="mr-2"
                />
                <label className="text-sm">Enter sleep when OBD bus is silent</label>
              </div>
            </PowerConditionCard>

            <PowerConditionCard
              title="Low Voltage Sleep (PDVS)"
              icon={<TrendingDown className="text-red-600" size={16} />}
              status={powerConfig.sleepConditions.voltage.enabled ? 'active' : 'normal'}
            >
              <div className="space-y-3">
                <div className="flex items-center">
                  <input
                    type="checkbox"
                    checked={powerConfig.sleepConditions.voltage.enabled}
                    onChange={(e) => updateSleepCondition('voltage', { enabled: e.target.checked })}
                    className="mr-2"
                  />
                  <label className="text-sm">Enable low voltage sleep</label>
                </div>
                
                {powerConfig.sleepConditions.voltage.enabled && (
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="block text-xs text-gray-600 mb-1">Threshold (V)</label>
                      <input
                        type="number"
                        step="0.1"
                        min="1.0"
                        max="25.0"
                        value={powerConfig.sleepConditions.voltage.threshold}
                        onChange={(e) => updateSleepCondition('voltage', { threshold: parseFloat(e.target.value) })}
                        className="w-full p-2 border rounded text-sm"
                      />
                    </div>
                    <div>
                      <label className="block text-xs text-gray-600 mb-1">Duration (sec)</label>
                      <input
                        type="number"
                        min="1"
                        max="65535"
                        value={powerConfig.sleepConditions.voltage.timer}
                        onChange={(e) => updateSleepCondition('voltage', { timer: parseInt(e.target.value) })}
                        className="w-full p-2 border rounded text-sm"
                      />
                    </div>
                  </div>
                )}
              </div>
            </PowerConditionCard>

            <PowerConditionCard
              title="Ignition Monitor"
              icon={<Zap className="text-orange-600" size={16} />}
              status={powerConfig.sleepConditions.ignition ? 'active' : 'normal'}
            >
              <div className="flex items-center">
                <input
                  type="checkbox"
                  checked={powerConfig.sleepConditions.ignition}
                  onChange={(e) => updateSleepCondition('ignition', e.target.checked)}
                  className="mr-2"
                />
                <label className="text-sm">Enter sleep when ignition goes low</label>
              </div>
            </PowerConditionCard>
          </div>
        </div>

        {/* Wake Conditions */}
        <div className="mb-8">
          <h2 className="text-xl font-bold text-gray-800 mb-4 flex items-center space-x-2">
            <Zap className="text-green-600" size={20} />
            <span>Wake Conditions</span>
          </h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <PowerConditionCard
              title="UART Activity"
              icon={<Settings className="text-gray-600" size={16} />}
              status={powerConfig.wakeConditions.uart ? 'active' : 'normal'}
            >
              <div className="flex items-center">
                <input
                  type="checkbox"
                  checked={powerConfig.wakeConditions.uart}
                  onChange={(e) => updateWakeCondition('uart', e.target.checked)}
                  className="mr-2"
                />
                <label className="text-sm">Wake on UART activity</label>
              </div>
            </PowerConditionCard>

            <PowerConditionCard
              title="OBD Bus Activity"
              icon={<Settings className="text-gray-600" size={16} />}
              status={powerConfig.wakeConditions.obd ? 'active' : 'normal'}
            >
              <div className="flex items-center">
                <input
                  type="checkbox"
                  checked={powerConfig.wakeConditions.obd}
                  onChange={(e) => updateWakeCondition('obd', e.target.checked)}
                  className="mr-2"
                />
                <label className="text-sm">Wake on OBD bus activity</label>
              </div>
            </PowerConditionCard>

            <PowerConditionCard
              title="Voltage Deep Drop (VDWK)"
              icon={<TrendingDown className="text-purple-600" size={16} />}
              status={powerConfig.wakeConditions.voltageDeepDrop.enabled ? 'active' : 'normal'}
            >
              <div className="space-y-3">
                <div className="flex items-center">
                  <input
                    type="checkbox"
                    checked={powerConfig.wakeConditions.voltageDeepDrop.enabled}
                    onChange={(e) => updateWakeCondition('voltageDeepDrop', { enabled: e.target.checked })}
                    className="mr-2"
                  />
                  <label className="text-sm">Wake on voltage deep drop</label>
                </div>
                
                {powerConfig.wakeConditions.voltageDeepDrop.enabled && (
                  <div>
                    <label className="block text-xs text-gray-600 mb-1">Drop Threshold (V)</label>
                    <input
                      type="number"
                      step="0.1"
                      min="0.1"
                      max="9.9"
                      value={powerConfig.wakeConditions.voltageDeepDrop.threshold}
                      onChange={(e) => updateWakeCondition('voltageDeepDrop', { threshold: parseFloat(e.target.value) })}
                      className="w-full p-2 border rounded text-sm"
                    />
                    <div className="text-xs text-gray-500 mt-1">
                      Wake when voltage drops by this amount
                    </div>
                  </div>
                )}
              </div>
            </PowerConditionCard>

            <PowerConditionCard
              title="Voltage Change Wake (VLCW) - NEW"
              icon={<TrendingUp className="text-blue-600" size={16} />}
              status={powerConfig.wakeConditions.voltageChange.enabled ? 'active' : 'normal'}
            >
              <div className="space-y-3">
                <div className="flex items-center">
                  <input
                    type="checkbox"
                    checked={powerConfig.wakeConditions.voltageChange.enabled}
                    onChange={(e) => updateWakeCondition('voltageChange', { enabled: e.target.checked })}
                    className="mr-2"
                  />
                  <label className="text-sm">Wake on voltage change</label>
                </div>
                
                {powerConfig.wakeConditions.voltageChange.enabled && (
                  <div className="space-y-2">
                    <div>
                      <label className="block text-xs text-gray-600 mb-1">Direction</label>
                      <select
                        value={powerConfig.wakeConditions.voltageChange.direction}
                        onChange={(e) => updateWakeCondition('voltageChange', { direction: e.target.value })}
                        className="w-full p-2 border rounded text-sm"
                      >
                        {VOLTAGE_DIRECTIONS.map(dir => (
                          <option key={dir.value} value={dir.value}>
                            {dir.label} {dir.description}
                          </option>
                        ))}
                      </select>
                    </div>
                    
                    <div className="grid grid-cols-2 gap-2">
                      <div>
                        <label className="block text-xs text-gray-600 mb-1">Threshold (V)</label>
                        <input
                          type="number"
                          step="0.1"
                          min="0.1"
                          max="8.0"
                          value={powerConfig.wakeConditions.voltageChange.threshold}
                          onChange={(e) => updateWakeCondition('voltageChange', { threshold: parseFloat(e.target.value) })}
                          className="w-full p-2 border rounded text-sm"
                        />
                      </div>
                      <div>
                        <label className="block text-xs text-gray-600 mb-1">Interval (ms)</label>
                        <input
                          type="number"
                          min="1"
                          max="65535"
                          value={powerConfig.wakeConditions.voltageChange.interval}
                          onChange={(e) => updateWakeCondition('voltageChange', { interval: parseInt(e.target.value) })}
                          className="w-full p-2 border rounded text-sm"
                        />
                      </div>
                    </div>
                    
                    <div className="text-xs text-gray-500">
                      Sampling at {(1000/powerConfig.wakeConditions.voltageChange.interval).toFixed(1)}Hz
                    </div>
                  </div>
                )}
              </div>
            </PowerConditionCard>
          </div>
        </div>

        {/* Generated Commands */}
        <div className="mt-8 p-4 bg-gray-50 rounded-lg">
          <h3 className="font-semibold mb-3 flex items-center space-x-2">
            <Settings size={16} />
            <span>Generated VT Commands</span>
          </h3>
          
          <div className="space-y-2">
            <div className="font-mono text-sm bg-white p-3 rounded border">
              <div className="text-blue-600 mb-2"># Query current power management status</div>
              <div>{generatePowerManageQuery()}</div>
            </div>
            
            {generatePowerCommands().map((cmd, index) => (
              <div key={index} className="font-mono text-sm bg-white p-3 rounded border">
                <div className="text-green-600">{cmd}</div>
              </div>
            ))}
            
            <div className="font-mono text-sm bg-white p-3 rounded border">
              <div className="text-purple-600 mb-2"># Real-time voltage monitoring</div>
              <div>{generateVoltageReadCommand()}</div>
            </div>
          </div>
        </div>

        {/* Power Management Features */}
        <div className="mt-8 p-4 bg-blue-50 rounded-lg">
          <h3 className="font-semibold mb-3">MIC3X2X Enhanced Power Features</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
            <div>
              <div className="font-medium text-blue-600 mb-2">Sleep Triggers:</div>
              <div className="space-y-1">
                <div>• UART silence detection</div>
                <div>• OBD bus silence detection</div>
                <div>• Low voltage threshold (PDVS)</div>
                <div>• Ignition pin monitoring</div>
                <div>• Battery voltage supervision</div>
              </div>
            </div>
            <div>
              <div className="font-medium text-green-600 mb-2">Wake Triggers:</div>
              <div className="space-y-1">
                <div>• UART activity detection</div>
                <div>• OBD bus activity detection</div>
                <div>• Voltage deep drop (VDWK)</div>
                <div>• Voltage change monitoring (VLCW) - NEW</div>
                <div>• Sleep current &lt; 3mA</div>
              </div>
            </div>
          </div>
          
          <div className="mt-4">
            <div className="font-medium text-purple-600 mb-2">NEW: Voltage Change Wake (VLCW)</div>
            <div className="text-xs space-y-1">
              <div>• Wake on voltage rise (+), drop (-), or both (±)</div>
              <div>• Configurable threshold (0.1V to 8.0V)</div>
              <div>• Programmable sampling interval (1-65535ms)</div>
              <div>• Real-time voltage monitoring at 4ms intervals</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MIC3X2XPowerManager;